### ISSUE TITLE
Empty JSON file

### ISSUE THREAD

**Issue by nikhiljha** [z3ntu/MonstercatConnectHelper#1]
Plugin produces an empty JSON file, which the downloader application obviously can't process.

**Comment by z3ntu** [comment]
~~The Connect website probably changed. I will look into it. Thanks.~~ EDIT: I just got the following file for download: [monstercatconnect.json](https://github.com/z3ntu/MonstercatConnectHelper/files/243783/monstercatconnect.json.txt). Does the console display anything and which Chrome version are you using?
EDIT 2: Oh were you in the "Catalog" view? It only works in the "Releases" view. I will try to hide the button when not in the correct view.

**Comment by nikhiljha** [comment]
Oh OK, then it was me being an idiot. Sorry! :P

**Comment by z3ntu** [comment]
No, no. It was not very clear why it didn't work. :)

**Comment by z3ntu** [comment]
btw please download a new version where I removed stuff which is no longer needed. Thanks :) [Download here](https://github.com/z3ntu/MonstercatConnectHelper/releases/latest)
